export const crystalFilters = [
  {
    'name':'Diameter',
    "items": [
      ['15 cm', '15-cm'],
      ['18 cm', '18-cm'],
      ['20 cm', '20-cm'],
      ['22 cm', '22-cm'],
      ['25 cm', '25-cm'],
    ]
  },
  {
    'name':'Crystal Type',
    'items':[
      ['Thaumatite', 'thaumatite'],
      ['Yilaster', 'yilaster'],
      ['Amisite', 'amisite'],
      ['Infused Quartz', 'infused-quartz'],
      ['Infused Obsidian', 'infused-obsidian'],
    ]
  },
  {
    'name':'Base Type',
    'items':[
      ['Old Oak', 'old-oak'],
      ['Old Pine', 'old-pine'],
      ['Maple', 'maple'],
    ]
  },
  {
    'name':'Aura',
    'items':[
      ['Chill', 'chill'],
      ['Ominous', 'ominous'],
      ['Spooky', 'spooky'],
      ['Warm', 'warm'],
      ['Freaky', 'freaky'],
    ]
  }
];

// MOST OF THEM HAVE BEEN RANDOMLY GENERATED BY CHAT GPT
export const crystalBallsItems = [
  {
    title: "Grade A Northern Mystic Ball",
    description: "RGB Lit, 15 cm Thaumatite. Gives off chill vibes. Sourced from the Northern Elder Elves Mine.",
    price: 245.0,
    color: 1 / 20,
    tags: ['15-cm', 'chill', 'old-pine', 'ominous']
  },
  {
    title: "Ultimate Ominous Hyper Ball",
    description: "20 cm. Infused Obsidian for all your wizardly needs. Nobody knows where it came from.",
    price: 245.0,
    color: 2 / 20,
    tags: ['20-cm', 'ominous', 'old-oak', 'spooky']
  },
  {
    title: "The Wizard's Favorite Chill Sphere",
    description: "18 cm Yilaster. Gives off chill vibes, perfect for those laid-back prophecy sessions. Made by gnomes under the Great Oak.",
    price: 325.0,
    color: 3 / 20,
    tags: ['18-cm', 'yilaster', 'old-oak', 'chill']
  },
  {
    title: "Elven Enchanted Mystery Orb",
    description: "25 cm Infused Quartz with a freaky aura. Legend says it was found in a forgotten elven ruin.",
    price: 510.0,
    color: 4 / 20,
    tags: ['25-cm', 'infused-quartz', 'maple', 'freaky']
  },
  {
    title: "Sorcerer's Supreme Vision",
    description: "22 cm Thaumatite. Radiates ominous energy, perfect for those deep, dark predictions. Crafted by the Dark Sorceress herself.",
    price: 475.0,
    color: 5 / 20,
    tags: ['22-cm', 'thaumatite', 'old-pine', 'ominous']
  },
  {
    title: "Chillaxed Seer's Orb",
    description: "15 cm Amisite. A soothing, chill vibe for the relaxed diviner. Carved from an ancient maple tree.",
    price: 280.0,
    color: 6 / 20,
    tags: ['15-cm', 'amisite', 'maple', 'chill']
  },
  {
    title: "Ominous Oracle Sphere",
    description: "20 cm Infused Obsidian. Ominous and spooky, perfect for Halloween fortune-telling.",
    price: 460.0,
    color: 7 / 20,
    tags: ['20-cm', 'infused-obsidian', 'old-oak', 'spooky']
  },
  {
    title: "Mystic Warmth Ball",
    description: "22 cm Yilaster. Radiates a warm, cozy energy. Ideal for winter prophecies by the fireplace.",
    price: 375.0,
    color: 8 / 20,
    tags: ['22-cm', 'yilaster', 'old-pine', 'warm']
  },
  {
    title: "Freaky Forest Oracle",
    description: "18 cm Infused Quartz. Freaky and mysterious, it’s said to be blessed by forest spirits.",
    price: 435.0,
    color: 9 / 20,
    tags: ['18-cm', 'infused-quartz', 'old-oak', 'freaky']
  },
  {
    title: "Spooktacular Vision Sphere",
    description: "20 cm Thaumatite. Gives off spooky vibes, ideal for haunted house readings.",
    price: 410.0,
    color: 10 / 20,
    tags: ['20-cm', 'thaumatite', 'maple', 'spooky']
  },
  {
    title: "Eldritch Seer's Ball",
    description: "25 cm Amisite. Ominous and eldritch, straight from the deep caverns of the unknown.",
    price: 580.0,
    color: 11 / 20,
    tags: ['25-cm', 'amisite', 'old-pine', 'ominous']
  },
  {
    title: "Warm Wizard's Orb",
    description: "15 cm Infused Obsidian. A warm glow perfect for enchanting evenings.",
    price: 290.0,
    color: 12 / 20,
    tags: ['15-cm', 'infused-obsidian', 'maple', 'warm']
  },
  {
    title: "The Lazy Wizard's Chillax Globe",
    description: "A 15 cm sphere of infused-quartz. Perfect for lazy afternoons and mellow prophecy sessions. Found under a dragon’s nap spot.",
    price: 260.0,
    color: 13 / 20,
    tags: ['15-cm', 'infused-quartz', 'maple', 'chill']
  },
  {
    title: "Grandma's Ancient Seeing Stone",
    description: "This 18 cm yilaster ball feels like it’s seen some things. If it could talk, it would probably tell you to get off its lawn.",
    price: 320.0,
    color: 14 / 20,
    tags: ['18-cm', 'yilaster', 'old-pine', 'ominous']
  },
  {
    title: "Spooky Spectacular Sphere",
    description: "A 22 cm ball made of infused-obsidian. It has this spooky aura that’s perfect for scaring your neighbors on Halloween.",
    price: 445.0,
    color: 15 / 20,
    tags: ['22-cm', 'infused-obsidian', 'old-oak', 'spooky']
  },
  {
    title: "The Freaky Oracle",
    description: "25 cm of freakiness wrapped in amisite. Definitely not something you'd want to stare at for too long. Legend has it that it once belonged to a prankster elf.",
    price: 490.0,
    color: 16 / 20,
    tags: ['25-cm', 'amisite', 'old-pine', 'freaky']
  },
  {
    title: "Warm Whispering Ball",
    description: "A 20 cm warm crystal ball that whispers comforting secrets. Perfect for cold nights when you need a friend.",
    price: 355.0,
    color: 17 / 20,
    tags: ['20-cm', 'infused-quartz', 'maple', 'warm']
  },
  {
    title: "Ominous Orb of Shadows",
    description: "This 22 cm thaumatite ball is perfect for those who thrive in darkness. Crafted in the deepest caves by shadow elves.",
    price: 510.0,
    color: 18 / 20,
    tags: ['22-cm', 'thaumatite', 'old-oak', 'ominous']
  },
  {
    title: "The Mysterious Dream Sphere",
    description: "An 18 cm infused-obsidian ball that’s said to bring weird dreams. Not for the faint of heart.",
    price: 420.0,
    color: 19 / 20,
    tags: ['18-cm', 'infused-obsidian', 'old-pine', 'spooky']
  },
  {
    title: "Gnome's Chill Globe",
    description: "A 15 cm sphere made of yilaster. It's been said that it’s been blessed by the gnomes of the Old Forest. Super chill vibes.",
    price: 270.0,
    color: 0 / 20,
    tags: ['15-cm', 'yilaster', 'maple', 'chill']
  },
  {
    title: "Freaky Fortune Teller",
    description: "20 cm of pure amisite freakiness. It's rumored to be able to predict the weirdest futures.",
    price: 475.0,
    color: 1 / 20,
    tags: ['20-cm', 'amisite', 'old-oak', 'freaky']
  },
  {
    title: "Ominous Overlord Orb",
    description: "25 cm of infused-quartz darkness. Perfect for the aspiring overlord. Stare into its depths and see your minions' fate.",
    price: 540.0,
    color: 2 / 20,
    tags: ['25-cm', 'infused-quartz', 'old-pine', 'ominous']
  },
  {
    title: "Elven Warm Light Sphere",
    description: "A cozy 18 cm ball of infused obsidian, said to contain the warmth of a thousand elven sunsets.",
    price: 360.0,
    color: 3 / 20,
    tags: ['18-cm', 'infused-obsidian', 'maple', 'warm']
  },
  {
    title: "The Spooky Whisperer",
    description: "22 cm of yilaster that whispers the spookiest secrets. Perfect for late-night ghost stories.",
    price: 430.0,
    color: 4 / 20,
    tags: ['22-cm', 'yilaster', 'old-oak', 'spooky']
  },
  {
    title: "Chill Enchanter's Orb",
    description: "20 cm of thaumatite, emitting the ultimate chill vibes. Ideal for those who like their magic laid-back.",
    price: 300.0,
    color: 5 / 20,
    tags: ['20-cm', 'thaumatite', 'old-pine', 'chill']
  },
  {
    title: "Mysterious Old Oak Sphere",
    description: "An 18 cm ball of amisite with an aura of mystery. Rumored to have been enchanted by an ancient wizard.",
    price: 395.0,
    color: 6 / 20,
    tags: ['18-cm', 'amisite', 'old-oak', 'ominous']
  },
  {
    title: "The Warm Glow Orb",
    description: "15 cm of warm yilaster goodness. Perfect for cozying up with a good spellbook.",
    price: 245.0,
    color: 7 / 20,
    tags: ['15-cm', 'yilaster', 'maple', 'warm']
  }
];